version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    restart: always

  app:
    build:
      context: .
    volumes:
      - ./py-test/app:/app/py-test
    command: sh -c "python3 app.py"
    depends_on:
      - selenium