version: '3'

services:
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
    restart: always

  robot-test:
    build:
      context: ./robot-test
    volumes:
      - ./robot-test/app/results:/app/robot-test/results
    command: sh -c "python3 app.py"
    depends_on:
      - selenium