version: '2'

services:
    chrome:
      image: selenium/standalone-chrome:latest
    app:
        build: .
        image: robot-test
        environment:
            WFIX_URL:
            WFIX_USERNAME:
            WFIX_PASSWORD:
        volumes:
            -  ./Results:/app/robot/Results
        depends_on:
            - chrome
            
